version: '3.7'
services:
  app:
    container_name: todo-list
    build:
      context: .
      args:
        JAR_FILE: /target/to-doList-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
      SPRING_REDIS_HOST: redis
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
      - redis
      - kafka
    restart: always
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
  redis:
    container_name: redis
    image: redis:5.0.5-alpine3.10
    ports:
      - "6379:6379"
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
